import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Brand & Greeting
    appName: 'Productivity OS',
    userName: 'Méhdi',
    badgeTag: 'Entrepreneur & High Performance ⚡',
    greeting: 'Hello Méhdi 👋',
    greetingSubtitle: 'Here is your high-performance operating system for today.',
    
    // Navigation
    navToday: 'Today',
    navWeek: 'Week',
    navProjects: 'Projects',
    navStats: 'Stats',
    navMonthlyReview: 'Monthly Review',
    navChallenge: '30-Day Challenge',
    navFocus: 'Focus Studio',
    navBriefing: 'Daily Journal',
    navCoach: 'AI Coach',
    navTutorial: 'App Tour & Guide',
    navInstall: 'Install on iPhone / Mobile',
    navClearSchedule: 'Clear All Scheduled Blocks',
    navResetConfirm: 'Are you sure you want to clear all blocks from your schedule? You will start with a fresh, empty week.',

    // Header & Actions
    syncLive: 'Cloud Synced',
    syncing: 'Syncing...',
    syncOffline: 'Offline Mode',
    refreshSync: 'Refresh cloud sync',
    newTask: 'New Task',
    newProject: 'New Project',
    themeDark: 'Dark mode',
    themeLight: 'Light mode',
    menu: 'Menu',
    close: 'Close',

    // Today Page
    scoreTitle: 'Daily Score',
    tasksTitle: 'Tasks Done',
    streakTitle: 'Active Streak',
    hydrationTitle: 'Hydration',
    targetMl: 'Goal: 1,925 ml',
    addWater: '+250 ml Water',
    todaySchedule: "Today's Schedule",
    blocksCount: (n) => `${n} block${n > 1 ? 's' : ''} scheduled`,
    validatedCount: (done, total) => `${done}/${total} completed`,
    noTasksToday: 'No blocks scheduled for today.',
    noTasksTodaySubtitle: 'Tap below to add your first task or schedule your day.',
    addFirstTask: '+ Add My First Task',
    markDone: 'Mark as done',
    startFocus: 'Focus',
    todayStatusClean: 'Clean Slate • Rest or Plan',

    // Dashboard Cards Evaluation & Helpers
    hydrationOptimal: 'Goal Reached (Optimal) 🏆',
    hydrationOptimalShort: 'Optimal ✅',
    hydrationGood: 'Good Level (On Track) ⚡',
    hydrationGoodShort: 'On Track ⚡',
    hydrationModerate: 'In Progress (Keep Going) ⏳',
    hydrationModerateShort: 'In Progress ⏳',
    hydrationStarted: 'Started (Drink Water) 💧',
    hydrationStartedShort: 'Started 💧',
    hydrationZero: '0 ml consumed (Let’s start) ⚠️',
    hydrationZeroShort: 'To Start ⚠️',
    hydrationReset: 'Reset to zero (0 ml)',
    hydrationResetTooltip: 'Reset to 0 ml',
    hydrationManageTitle: 'Manage Hydration',
    hydrationCurrentAndGoal: (cur, goal) => `Current: ${cur} ml / Goal: ${goal} ml`,
    hydrationSubtract: 'Subtract 250ml',
    hydrationAdd: 'Add 250ml',
    hydrationInvalidAmount: 'Invalid amount',
    days: 'days',
    day: 'day',
    streakActive: 'Active Streak',
    streakCurrent: 'Current streak',
    tasksCompleted: 'completed',
    tasksRemaining: 'Remaining tasks',

    // Notifications & Pop-ups
    notifBadgeActive: 'Alerts Active',
    notifBadgeEnable: 'Enable Alerts',
    notifBadgeTitleActive: 'System notifications active (Click to test)',
    notifBadgeTitleEnable: 'Enable system notifications (Schedule & Focus pop-ups)',
    notifMenuTitle: 'Notifications active',
    notifMenuDesc: 'Your phone or desktop will display a pop-up alert at the exact start of your scheduled tasks and at the end of your focus sessions.',
    notifMenuTestBtn: 'Send a test notification now',
    notifMenuSending: 'Sending test...',
    notifBannerTitle: 'Enable Pop-up Alerts (WhatsApp Style)',
    notifBannerBadge: 'Recommended',
    notifBannerDesc: 'Get instant alerts on your phone or PC as soon as an agenda block starts or a focus timer finishes, even when the browser is closed.',
    notifBannerDismiss: 'Later',
    notifBannerEnable: 'Enable Alerts',
    notifBannerActivating: 'Activating...',

    // PWA Welcome Auto Install Modal
    pwaAutoTitle: 'Install Productivity OS on your phone',
    pwaAutoSubtitle: 'Run Productivity OS as a full native app directly from your Home Screen with zero browser bars and offline capability.',
    pwaAutoLater: 'Maybe later',
    pwaAutoInstall: 'Install Now',

    // Focus Studio
    focusTitle: 'Focus Studio',
    focusSubtitle: 'Science-backed protocols to achieve deep flow state',
    focusScienceBadge: 'Focus Science',
    focusPickMethod: 'Choose a focus method',
    focusProtocol: 'Execution Protocol:',
    focusBy: 'by',
    focusPhaseWork: (m) => `⚡ Work (${m}m)`,
    focusPhaseBreak: (m) => `☕ Break (${m}m)`,
    focusPhaseLongBreak: (m) => `🌿 Long Break (${m}m)`,
    focusCycleStatus: (curr, max) => `Cycle ${curr} / ${max} — Absolute focus`,
    focusBreakStatus: 'Active recovery — stretch, hydrate, and rest your eyes',
    focusStart: 'Start Focus',
    focusPause: 'Pause Session',
    focusReset: 'Reset',
    focusSoundActive: 'Sound Active',
    focusSoundMuted: 'Sound Muted',
    focusTestSound: 'Test sound',
    focusPlayingSound: 'Playing...',
    focusExpand: 'Expand timer',

    // Daily Briefing
    briefingTitle: 'Daily Journal & Briefing',
    yesterdayScoreTitle: "Yesterday's Score",
    activeStreakTitle: 'Active Streak',
    streakUnit: (n) => `${n} day${n > 1 ? 's' : ''}`,
    streakOn: '🔥 Streak in progress!',
    streakZero: 'Ready for your 1st day',
    weeklyTrendTitle: 'Past 7 Days Trend',
    averageBadge: (avg) => `Average: ${avg}%`,
    todayTargetTitle: "Today's Schedule & Targets",
    activeProjectsTitle: 'Active Projects',
    openAiCoach: 'Open AI Coach',
    startDay: "Let's Start the Day 🚀",

    // Priority Coach
    coachTitle: 'AI Priority Coach',
    coachSubtitle: 'Smart Scheduling & Free Slot Optimization',
    coachProactiveTitle: 'Proactive AI Analysis',
    coachFreeSlot: 'Free slot:',
    coachApply: 'Apply',
    coachTabSuggestions: '⚡ Suggestions',
    coachTabMatrix: '🎯 Matrix',
    coachTabSlots: '🕒 Free Slots',
    coachOptimalFound: 'Optimal Schedule Match Detected',
    coachScheduleInSlot: 'Schedule Task in Slot',
    coachLaunchFocus: 'Focus Now',
    coachNoFreeSlots: 'No free slots over 30 mins available today.',
    coachNoTasks: 'No active tasks found in projects.',

    // Projects Page & Modals
    projectsTitle: 'Strategic Goals & Projects',
    projectsSubtitle: 'Define your tasks and milestones. Progress and deadlines are calculated automatically.',
    filterByPriority: 'Priority Filter:',
    filterByStatus: 'Status Filter:',
    all: 'All',
    urgent: 'Urgent',
    important: 'Important',
    normal: 'Normal',
    low: 'Low',
    notStarted: 'Not Started',
    inProgress: 'In Progress',
    overdue: 'Overdue',
    done: 'Done',
    noProjectsFound: 'No projects match your active filters.',
    resetFilters: 'Reset filters',
    addSubtask: 'Add Subtask',
    subtaskPlaceholder: 'Type a new subtask and press enter...',
    deadline: 'Deadline',
    progress: 'Progress',
    noSubtasks: 'No subtasks yet. Add one to start progressing!',
    newProjectModalTitle: '📁 New Strategic Project',
    editProjectModalTitle: 'Edit Project',
    projectNameLabel: 'Project Name',
    projectNamePlaceholder: 'e.g. Brand Identity, Client Strategy...',
    projectPriorityLabel: 'Project Importance & Priority',
    categoryLabel: 'Category or Client',
    deadlineLabel: 'Target Deadline',
    initialStatusLabel: 'Initial Status',
    projectStatusLabel: 'Project Status',
    descriptionLabel: 'Short Description & Objectives',
    createProjectBtn: 'Create Project',
    saveProjectBtn: 'Save Changes',
    deleteProjectBtn: 'Delete Project',
    deleteProjectConfirm: 'Are you sure you want to delete this project?',
    finishedEarly: (d) => `✅ Finished ${d} day${d > 1 ? 's' : ''} early`,
    finishedOnTime: '✅ Finished on the day',
    finishedLate: (d) => `✅ Finished with ${d} day${d > 1 ? 's' : ''} delay`,
    dueToday: 'Due today!',
    dueInDays: (d) => `In ${d} day${d > 1 ? 's' : ''}`,
    overdueBy: (d) => `Overdue (${d}d)`,
    tasksCount: (done, total) => `Tasks (${done}/${total})`,
    noTasksYet: 'No tasks defined. Add your 1st task below:',

    // Stats Page
    statsTitle: 'Performance & Analytics',
    weeklyAverage: 'Weekly Average',
    completionRate: 'Completion Rate',
    totalFocusHours: 'Total Focus Hours',
    hydrationScore: 'Hydration Consistency',
    performanceHistory: 'Past 7 Days History',
    bestDay: 'Best Day',
    peakProductivity: 'Peak productivity score',
    noSessionLogged: 'No session logged',
    averageScore: 'Average Score',
    weeklyAverageFull: 'Weekly Average (Mon-Sun)',
    currentWeekDesc: 'Current week (Monday to Sunday)',
    pastDaysDesc: (d) => `Over the past ${d} days`,
    averageHydration: 'Average Hydration',
    hydrationTargetDesc: (pct, met, total) => `${pct}% of target (${met}/${total}d reached)`,
    dateReport: (dateStr) => `Summary for ${dateStr}`,
    scoreDetail: (s, c, t) => `Score: ${s}% • ${c}/${t} blocks completed`,
    noActivityOnDate: (d) => `No activity logged for this date (${d}).`,
    hydrationDetail: (curr, target) => `Hydration: ${curr} ml / ${target} ml`,
    hydration100Reached: 'Goal 100%+ Reached ✅',
    hydrationPercentOfTarget: (pct) => `${pct}% of target ⏳`,
    hydrationNotLogged: '0 ml drank (Not logged) ⚠️',
    dailyScoreLabel: 'Daily Score',
    statusLabel: 'Status',
    productivityScoreChart: 'Productivity Score',
    hydrationVolumeChart: 'Hydration Volume',
    chartScoreSubtitle: 'Checkable blocks completion rate',
    chartHydrationSubtitle: 'Daily water volume vs 1,925 ml target',
    past4WeeksTitle: 'Past 4 Weeks Evolution',
    consistencySubtitle: 'Consistency and regularity over time',
    historyBadge: 'History',
    targetWaterLabel: 'Target 1925 ml',
    waterUnit: 'Water',

    // Calendar
    weekTitle: 'Weekly Schedule',
    view1Day: '1 Day',
    view3Days: '3 Days',
    viewWeek: '7 Days',
    emptySlotPrompt: 'Tap any hour slot to add a block',
    emptyDayTitle: 'No blocks scheduled for this day',
    addBlockToDay: '+ Add block',
    editBlock: 'Edit Block',
    deleteBlock: 'Delete Block',
    saveBlock: 'Save Changes',
    blockTitlePlaceholder: 'e.g. Client Call, Deep Work, Gym...',
    blockStartTime: 'Start Time',
    blockEndTime: 'End Time',
    blockColor: 'Color',
    blockCheckable: 'Include in daily score checklist',
    todayBadge: 'Today',
    todayShort: 'Today',
    selectedBadge: 'Selected',
    todayIncluded: 'Today included',
    thisWeek: 'This week',
    weekOfRange: (startDay, startMonth, endDay, endMonth) => `Week of ${startDay} ${startMonth} to ${endDay} ${endMonth}`,
    view1DayDesc: (range) => `Detailed 1-day view • ${range}`,
    view3DaysDesc: (range) => `3-consecutive-day view • ${range}`,
    viewWeekDesc: 'Full week (7 days) • Live view of schedule slots and project deadlines.',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    prevDay: 'Previous day',
    nextDay: 'Next day',
    addSlot: '+ Add slot',
    chooseDay: 'Select day:',
    dropToReschedule: 'Drop to reschedule',
    projectDeadline: 'Project Deadline',
    permanentRoutine: 'Permanent Daily Routine',
    permanentRoutineDesc: 'Repeats every day across all weeks',
    singleDayTaskDesc: 'Single-day task only',

    // Agenda Availability & Conflict Detection
    slotConflictTitle: 'Slot already taken!',
    slotConflictWarning: (title, start, end) => `This slot is already booked by "${title}" (${start} - ${end}).`,
    slotConflictAdvice: 'To prevent overlapping activities, please pick an available slot.',
    shiftAfterSlot: (time) => `⚡ Shift after this task (${time})`,
    availableSlotsTitle: 'Recommended free slots',
    alreadyBookedTitle: 'Already booked on this day',
    noBookedSlots: 'No booked tasks on this day (100% free)',
    slotBlocked: 'Taken',
    slotAvailable: 'Free',
    slotInvalidDuration: 'End time must be after start time',
    btnSlotConflictDisabled: 'Slot unavailable (conflict)',
    chooseQuickSlot: 'Quick hour selection:',
    aiSmartSchedulerTitle: 'AI Smart Slot Suggestions',
    aiSmartSchedulerSubtitle: 'Intelligent slots adapted to task nature & biological energy peaks',
    aiUpcomingOnly: 'Upcoming slots only (today)',
    aiEstimatedDuration: (dur) => `Estimated duration: ~${dur}`,
    aiNoSlotsToday: 'No suitable open slot found for this duration today. Consider scheduling tomorrow or picking a shorter duration.',

    // Modals generic
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    save: 'Save',
    create: 'Create',
    projectName: 'Project Name',
    projectSubtitle: 'Category or Client',
    projectDescription: 'Description & Objectives',
    dueDate: 'Target Deadline',

    // Install Modal
    installModalTitle: 'Install on your iPhone',
    installModalSubtitle: 'Run Productivity OS as a full native app directly from your Home Screen with zero URL bar.',
    installStep1Title: '1. Tap the Share button',
    installStep1Desc: 'In the bottom toolbar of Safari, tap the Share icon (square with arrow pointing up).',
    installStep2Title: '2. Tap "Add to Home Screen"',
    installStep2Desc: 'Scroll down the list and select the option with the plus (+) icon.',
    installStep3Title: '3. Tap "Add"',
    installStep3Desc: 'Tap "Add" at the top right of your screen. Done! The app icon is now on your phone.',
    installGotIt: 'Got it, thanks!',
    installAndroidTitle: 'Install App',
    installAndroidDesc: 'Click install to add this application to your phone or desktop.',
    installNow: 'Install Now',

    // Onboarding Tour
    tourTitle: 'Welcome, Emmanuella! 🎉',
    tourStep1Title: 'Your Personal Operating System',
    tourStep1Desc: 'This app is customized specifically for you to manage your days, projects, habits, and focus sessions effortlessly right from your phone.',
    tourStep2Title: 'Today Dashboard',
    tourStep2Desc: 'Check your daily performance score, log your hydration with 1 tap, and check off your completed blocks throughout the day.',
    tourStep3Title: 'Week Planning',
    tourStep3Desc: 'Organize your schedule day by day. Simply tap on any empty slot to add a block or adjust your timings.',
    tourStep4Title: 'Projects & Tasks',
    tourStep4Desc: 'Break your big goals into bite-sized actionable subtasks. Each checked subtask automatically updates your project progress.',
    tourStep5Title: 'Focus Studio & AI Coach',
    tourStep5Desc: 'Launch distraction-free Pomodoro or Deep Work sessions and use the AI Coach to optimize your priorities.',
    tourNext: 'Next',
    tourPrev: 'Back',
    tourFinish: "Let's Get Started 🚀",
    tourSkip: 'Skip Tour'
  },
  fr: {
    // Brand & Greeting
    appName: 'Productivity OS',
    userName: 'Méhdi',
    badgeTag: 'Entrepreneur & High Performance ⚡',
    greeting: 'Bonjour Méhdi 👋',
    greetingSubtitle: 'Voici votre système de haute performance pour aujourd’hui.',
    
    // Navigation
    navToday: 'Aujourd’hui',
    navWeek: 'Semaine',
    navProjects: 'Projets',
    navStats: 'Statistiques',
    navMonthlyReview: 'Bilan Mensuel',
    navChallenge: 'Défi 30 Jours',
    navFocus: 'Studio Focus',
    navBriefing: 'Journal du jour',
    navCoach: 'Coach IA',
    navTutorial: 'Guide & Tutoriel',
    navInstall: 'Installer sur iPhone / Mobile',
    navClearSchedule: 'Vider le calendrier de la semaine',
    navResetConfirm: 'Êtes-vous sûre de vouloir effacer tous les blocs de votre calendrier ? Vous repartirez sur une semaine totalement vierge.',

    // Header & Actions
    syncLive: 'Cloud Synchro',
    syncing: 'Synchronisation...',
    syncOffline: 'Mode Hors-ligne',
    refreshSync: 'Actualiser la synchronisation',
    newTask: 'Nouvelle Tâche',
    newProject: 'Nouveau Projet',
    themeDark: 'Mode sombre',
    themeLight: 'Mode clair',
    menu: 'Menu',
    close: 'Fermer',

    // Today Page
    scoreTitle: 'Score du Jour',
    tasksTitle: 'Tâches Validées',
    streakTitle: 'Série Active',
    hydrationTitle: 'Hydratation',
    targetMl: 'Objectif : 1 925 ml',
    addWater: '+250 ml d’eau',
    todaySchedule: 'Programme du Jour',
    blocksCount: (n) => `${n} bloc${n > 1 ? 's' : ''} planifié${n > 1 ? 's' : ''}`,
    validatedCount: (done, total) => `${done}/${total} validés`,
    noTasksToday: 'Aucun bloc planifié pour aujourd’hui.',
    noTasksTodaySubtitle: 'Appuyez ci-dessous pour ajouter votre première tâche ou organiser votre journée.',
    addFirstTask: '+ Ajouter ma première tâche',
    markDone: 'Marquer comme fait',
    startFocus: 'Focus',
    todayStatusClean: 'Planning libre • Repos ou Plan',

    // Dashboard Cards Evaluation & Helpers
    hydrationOptimal: 'Objectif Atteint (Optimal) 🏆',
    hydrationOptimalShort: 'Optimal ✅',
    hydrationGood: 'Bon niveau (En bonne voie) ⚡',
    hydrationGoodShort: 'Bon niveau ⚡',
    hydrationModerate: 'En cours (À poursuivre) ⏳',
    hydrationModerateShort: 'En cours ⏳',
    hydrationStarted: 'Démarré (Pensez à boire) 💧',
    hydrationStartedShort: 'Démarré 💧',
    hydrationZero: '0 ml bus (À démarrer) ⚠️',
    hydrationZeroShort: 'À démarrer ⚠️',
    hydrationReset: 'Remettre à zéro (0 ml)',
    hydrationResetTooltip: 'Remettre à 0 ml',
    hydrationManageTitle: 'Gérer l’hydratation',
    hydrationCurrentAndGoal: (cur, goal) => `Actuel : ${cur} ml / Objectif : ${goal} ml`,
    hydrationSubtract: 'Retirer 250ml',
    hydrationAdd: 'Ajouter 250ml',
    hydrationInvalidAmount: 'Montant invalide',
    days: 'jours',
    day: 'jour',
    streakActive: 'Série Active',
    streakCurrent: 'Série actuelle',
    tasksCompleted: 'complétées',
    tasksRemaining: 'Tâches restantes',

    // Notifications & Pop-ups
    notifBadgeActive: 'Alertes Actives',
    notifBadgeEnable: 'Activer Pop-ups',
    notifBadgeTitleActive: 'Notifications système actives (Cliquer pour tester)',
    notifBadgeTitleEnable: 'Activer les alertes pop-up système (Agenda & Focus)',
    notifMenuTitle: 'Notifications actives',
    notifMenuDesc: 'Votre téléphone ou ordinateur émettra un pop-up à l’heure exacte de vos tâches d’agenda et à la fin de vos sessions de focus.',
    notifMenuTestBtn: 'Tester une notification maintenant',
    notifMenuSending: 'Envoi en cours...',
    notifBannerTitle: 'Activer les alertes pop-up (Style WhatsApp)',
    notifBannerBadge: 'Recommandé',
    notifBannerDesc: 'Recevez une notification sur votre téléphone ou PC dès qu’un créneau d’agenda démarre ou qu’un minuteur de focus se termine, même application fermée.',
    notifBannerDismiss: 'Plus tard',
    notifBannerEnable: 'Activer',
    notifBannerActivating: 'Activation...',

    // PWA Welcome Auto Install Modal
    pwaAutoTitle: 'Installez Productivity OS sur votre smartphone',
    pwaAutoSubtitle: 'Profitez d’une véritable application mobile sans barre d’adresse, avec ouverture instantanée et accès hors-ligne.',
    pwaAutoLater: 'Plus tard',
    pwaAutoInstall: 'Installer maintenant',

    // Focus Studio
    focusTitle: 'Studio de Concentration',
    focusSubtitle: 'Techniques scientifiquement éprouvées pour atteindre l’état de flow',
    focusScienceBadge: 'Science du Focus',
    focusPickMethod: 'Choisir une méthode de travail',
    focusProtocol: 'Protocole d’exécution :',
    focusBy: 'par',
    focusPhaseWork: (m) => `⚡ Travail (${m}m)`,
    focusPhaseBreak: (m) => `☕ Pause (${m}m)`,
    focusPhaseLongBreak: (m) => `🌿 Grande Pause (${m}m)`,
    focusCycleStatus: (curr, max) => `Cycle ${curr} / ${max} — Focus absolu`,
    focusBreakStatus: 'Repos actif — étirez-vous, buvez de l’eau et reposez vos yeux',
    focusStart: 'Démarrer le Focus',
    focusPause: 'Mettre en pause',
    focusReset: 'Réinitialiser',
    focusSoundActive: 'Sonnerie Active',
    focusSoundMuted: 'Son Coupé',
    focusTestSound: 'Tester le son',
    focusPlayingSound: 'Lecture...',
    focusExpand: 'Agrandir le minuteur',

    // Daily Briefing
    briefingTitle: 'Journal Quotidien & Briefing',
    yesterdayScoreTitle: "Score d'hier",
    activeStreakTitle: 'Série Active',
    streakUnit: (n) => `${n} jour${n > 1 ? 's' : ''}`,
    streakOn: '🔥 Série en cours !',
    streakZero: 'Prêt pour votre 1ère journée',
    weeklyTrendTitle: 'Tendance des 7 derniers jours',
    averageBadge: (avg) => `Moyenne : ${avg}%`,
    todayTargetTitle: 'Programme & Objectifs du jour',
    activeProjectsTitle: 'Projets en cours',
    openAiCoach: 'Ouvrir le Coach IA',
    startDay: 'Commencer ma journée 🚀',

    // Priority Coach
    coachTitle: 'Coach de Priorités IA',
    coachSubtitle: 'Ordonnancement & Créneaux Intelligents',
    coachProactiveTitle: 'Analyse IA Proactive',
    coachFreeSlot: 'Créneau libre :',
    coachApply: 'Appliquer',
    coachTabSuggestions: '⚡ Suggestions',
    coachTabMatrix: '🎯 Matrice',
    coachTabSlots: '🕒 Créneaux',
    coachOptimalFound: 'Planification Optimale Détectée',
    coachScheduleInSlot: 'Planifier dans ce créneau',
    coachLaunchFocus: 'Lancer en Focus',
    coachNoFreeSlots: 'Aucun créneau libre de +30 min aujourd’hui.',
    coachNoTasks: 'Aucune tâche active trouvée dans les projets.',

    // Projects Page & Modals
    projectsTitle: 'Projets Stratégiques & Objectifs',
    projectsSubtitle: 'Définissez vos tâches et étapes clés. La progression et le suivi des échéances sont automatisés.',
    filterByPriority: 'Filtrer par Priorité :',
    filterByStatus: 'Filtrer par Statut :',
    all: 'Tous',
    urgent: 'Urgent',
    important: 'Important',
    normal: 'Normal',
    low: 'Faible',
    notStarted: 'Non commencé',
    inProgress: 'En cours',
    overdue: 'En retard',
    done: 'Terminé',
    noProjectsFound: 'Aucun projet ne correspond à vos filtres actifs.',
    resetFilters: 'Réinitialiser les filtres',
    addSubtask: 'Ajouter une sous-tâche',
    subtaskPlaceholder: 'Tapez une sous-tâche et appuyez sur entrée...',
    deadline: 'Échéance',
    progress: 'Progression',
    noSubtasks: 'Aucune sous-tâche pour le moment. Ajoutez-en une pour avancer !',
    newProjectModalTitle: '📁 Nouveau Projet Stratégique',
    editProjectModalTitle: 'Modifier le Projet',
    projectNameLabel: 'Nom du projet',
    projectNamePlaceholder: 'ex: Portail Patient, Lancement Marque...',
    projectPriorityLabel: 'Importance / Priorité du projet',
    categoryLabel: 'Catégorie ou Client',
    deadlineLabel: 'Date d’échéance (Deadline)',
    initialStatusLabel: 'Statut initial',
    projectStatusLabel: 'Statut du projet',
    descriptionLabel: 'Description courte & Objectifs',
    createProjectBtn: 'Créer le projet',
    saveProjectBtn: 'Enregistrer',
    deleteProjectBtn: 'Supprimer le projet',
    deleteProjectConfirm: 'Êtes-vous sûre de vouloir supprimer ce projet ?',
    finishedEarly: (d) => `✅ Terminé ${d} jour${d > 1 ? 's' : ''} avant`,
    finishedOnTime: '✅ Terminé le jour même',
    finishedLate: (d) => `✅ Terminé avec ${d} jour${d > 1 ? 's' : ''} de retard`,
    dueToday: "Aujourd'hui !",
    dueInDays: (d) => `Dans ${d} jour${d > 1 ? 's' : ''}`,
    overdueBy: (d) => `En retard (${d}j)`,
    tasksCount: (done, total) => `Tâches (${done}/${total})`,
    noTasksYet: 'Aucune tâche définie. Ajoutez votre 1ère tâche ci-dessous :',

    // Stats Page
    statsTitle: 'Performances & Analyses',
    weeklyAverage: 'Moyenne Hebdomadaire',
    completionRate: 'Taux de Complétion',
    totalFocusHours: 'Heures de Focus Total',
    hydrationScore: 'Régularité Hydratation',
    performanceHistory: 'Historique des 7 derniers jours',
    bestDay: 'Meilleur Jour',
    peakProductivity: 'Score de productivité maximal',
    noSessionLogged: 'Aucune session enregistrée',
    averageScore: 'Score Moyen',
    weeklyAverageFull: 'Moyenne Semaine (Lun-Dim)',
    currentWeekDesc: 'Semaine en cours (Lundi à Dimanche)',
    pastDaysDesc: (d) => `Sur les ${d} derniers jours`,
    averageHydration: 'Hydratation Moyenne',
    hydrationTargetDesc: (pct, met, total) => `${pct}% de la cible (${met}/${total}j atteints)`,
    dateReport: (dateStr) => `Bilan du ${dateStr}`,
    scoreDetail: (s, c, t) => `Score : ${s}% • ${c}/${t} blocs complétés`,
    noActivityOnDate: (d) => `Aucune activité enregistrée à cette date (${d}).`,
    hydrationDetail: (curr, target) => `Hydratation : ${curr} ml / ${target} ml`,
    hydration100Reached: 'Objectif 100%+ Atteint ✅',
    hydrationPercentOfTarget: (pct) => `${pct}% de la cible ⏳`,
    hydrationNotLogged: '0 ml bus (Non renseigné) ⚠️',
    dailyScoreLabel: 'Score Jour',
    statusLabel: 'Statut',
    productivityScoreChart: 'Score de Productivité',
    hydrationVolumeChart: "Volume d'Hydratation",
    chartScoreSubtitle: "Taux d'accomplissement des blocs checkables",
    chartHydrationSubtitle: "Suivi du volume d'eau bu par jour vs cible 1 925 ml",
    past4WeeksTitle: 'Évolution des 4 Dernières Semaines',
    consistencySubtitle: 'Régularité et constance dans le temps',
    historyBadge: 'Historique',
    targetWaterLabel: 'Cible 1925 ml',
    waterUnit: 'Eau',

    // Calendar
    weekTitle: 'Planning de la Semaine',
    view1Day: '1 Jour',
    view3Days: '3 Jours',
    viewWeek: '7 Jours',
    emptySlotPrompt: 'Touchez un créneau horaire pour ajouter un bloc',
    emptyDayTitle: 'Aucun bloc prévu pour ce jour',
    addBlockToDay: '+ Ajouter un bloc',
    editBlock: 'Modifier le bloc',
    deleteBlock: 'Supprimer le bloc',
    saveBlock: 'Enregistrer',
    blockTitlePlaceholder: 'Ex : Appel client, Deep Work, Sport...',
    blockStartTime: 'Heure de début',
    blockEndTime: 'Heure de fin',
    blockColor: 'Couleur',
    blockCheckable: 'Inclure dans le score du jour',
    todayBadge: "Aujourd'hui",
    todayShort: 'Auj.',
    selectedBadge: 'Sélectionné',
    todayIncluded: "Aujourd'hui inclus",
    thisWeek: 'Cette semaine',
    weekOfRange: (startDay, startMonth, endDay, endMonth) => `Semaine du ${startDay} ${startMonth} au ${endDay} ${endMonth}`,
    view1DayDesc: (range) => `Vue détaillée 1 jour • ${range}`,
    view3DaysDesc: (range) => `Vue 3 jours consécutifs • ${range}`,
    viewWeekDesc: 'Semaine complète (7 jours) • Visualisation en direct des créneaux et échéances projets.',
    prevWeek: 'Semaine précédente',
    nextWeek: 'Semaine suivante',
    prevDay: 'Jour précédent',
    nextDay: 'Jour suivant',
    addSlot: '+ Ajouter un créneau',
    chooseDay: 'Choisir un jour :',
    dropToReschedule: 'Déposer pour replanifier',
    projectDeadline: 'Échéance Projet',
    permanentRoutine: 'Routine quotidienne permanente',
    permanentRoutineDesc: 'Se répète chaque jour sur toutes les semaines',
    singleDayTaskDesc: 'Activité pour cette date uniquement',

    // Agenda Availability & Conflict Detection
    slotConflictTitle: 'Ce créneau a déjà été pris !',
    slotConflictWarning: (title, start, end) => `Ce créneau a déjà été pris par « ${title} » (${start} - ${end}).`,
    slotConflictAdvice: 'Pour éviter que les activités ne s’empilent, veuillez choisir un créneau libre.',
    shiftAfterSlot: (time) => `⚡ Décaler après cette tâche (${time})`,
    availableSlotsTitle: 'Créneaux libres recommandés',
    alreadyBookedTitle: 'Déjà réservé sur cette journée',
    noBookedSlots: 'Aucun créneau réservé (journée 100% libre)',
    slotBlocked: 'Pris',
    slotAvailable: 'Libre',
    slotInvalidDuration: 'L’heure de fin doit être après l’heure de début',
    btnSlotConflictDisabled: 'Créneau indisponible (conflit)',
    chooseQuickSlot: 'Choix rapide de l’heure :',
    aiSmartSchedulerTitle: 'Suggestions Intelligentes de l’IA',
    aiSmartSchedulerSubtitle: 'Créneaux intelligents adaptés à la tâche et aux pics d’énergie',
    aiUpcomingOnly: 'Créneaux à venir uniquement (aujourd’hui)',
    aiEstimatedDuration: (dur) => `Durée estimée : ~${dur}`,
    aiNoSlotsToday: 'Aucun créneau libre adapté disponible pour cette durée aujourd’hui. Planifiez pour demain ou réduisez la durée.',

    // Modals generic
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    save: 'Enregistrer',
    create: 'Créer',
    projectName: 'Nom du Projet',
    projectSubtitle: 'Catégorie ou Client',
    projectDescription: 'Description & Objectifs',
    dueDate: 'Date limite',

    // Install Modal
    installModalTitle: 'Installer sur votre iPhone',
    installModalSubtitle: 'Utilisez Productivity OS comme une véritable application native directement depuis votre écran d’accueil.',
    installStep1Title: '1. Appuyez sur le bouton Partager',
    installStep1Desc: 'Dans la barre inférieure de Safari, appuyez sur l’icône de partage (carré avec la flèche vers le haut).',
    installStep2Title: '2. Choisissez "Sur l’écran d’accueil"',
    installStep2Desc: 'Faites défiler la liste vers le bas et sélectionnez l’option avec l’icône (+).',
    installStep3Title: '3. Validez "Ajouter"',
    installStep3Desc: 'Appuyez sur "Ajouter" en haut à droite. L’icône apparaîtra sur votre iPhone.',
    installGotIt: 'C’est compris !',
    installAndroidTitle: 'Installer l’application',
    installAndroidDesc: 'Cliquez sur installer pour ajouter l’application à votre smartphone ou ordinateur.',
    installNow: 'Installer maintenant',

    // Onboarding Tour
    tourTitle: 'Bienvenue Emmanuella ! 🎉',
    tourStep1Title: 'Votre Système Opérationnel Personnel',
    tourStep1Desc: 'Cette application a été conçue pour vous permettre de piloter vos journées, vos projets et vos sessions de travail en toute simplicité depuis votre smartphone.',
    tourStep2Title: 'Tableau de bord Aujourd’hui',
    tourStep2Desc: 'Suivez votre score d’accomplissement, enregistrez votre eau en 1 clic et cochez vos blocs au fur et à mesure.',
    tourStep3Title: 'Planning Semaine',
    tourStep3Desc: 'Planifiez vos journées bloc par bloc. Touchez simplement un créneau horaire vide pour créer un rendez-vous ou une tâche.',
    tourStep4Title: 'Projets & Sous-tâches',
    tourStep4Desc: 'Découpez vos grands objectifs en sous-tâches concrètes. Chaque sous-tâche cochée fait progresser votre projet automatiquement.',
    tourStep5Title: 'Studio Focus & Coach IA',
    tourStep5Desc: 'Lancez des sessions Pomodoro sans distraction et sollicitez le Coach IA pour prioriser votre journée.',
    tourNext: 'Suivant',
    tourPrev: 'Précédent',
    tourFinish: 'C’est parti ! 🚀',
    tourSkip: 'Passer le tour'
  }
};

export const LanguageProvider = ({ children }) => {
  // Strict default to English ('en') for Emmanuella, with seamless switch to French ('fr')
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('pos_lang');
    if (saved && (saved === 'en' || saved === 'fr')) return saved;
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('pos_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'fr' : 'en'));
  };

  const t = (key, ...args) => {
    const val = translations[lang]?.[key] || translations['en']?.[key] || key;
    if (typeof val === 'function') {
      return val(...args);
    }
    return val;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
